### ISSUE TITLE
Operating time on battery ?

### ISSUE THREAD

**Issue by minigranis** [VladimirV01/t5_informer#4]
Hello.
Intresting projekt, can you tell me how long the battery lasts in your application ?

Brg

**Comment by VladimirV01** [comment]
Hello.

This is complex question. In my application with the code posted on the repository it was working around 5-6 days for me when the battery was healthy. And this was way below my expectations. It demotivated me to work on improving the project.

Since then, I have discharged the battery under the lower allowed threshold and its capacity has degraded. Now it works around 3 days on a charge.

Over discharging the battery is really a concern in this application because the board has no protection integrated for this scenario. You should either send some alarms to your phone from HASS when the battery is low, and charge it before its voltage is below allowed values or add a cheap battery protection PCB, which will protect the battery. 

Also, there are several improvements which can be made to the code and this should have significant impact on battery life.
1. Improve the code to update only once after wake up, when all the needed data is collected and ready to be presented. _Currently it updates 3 or 4 times when it wakes up._
2. Make the sleep time adaptive and don't wake up ad night.
3. Keep track if there is somebody at home or not. If nobody is at home, immediately go back to sleep without updating the screen.

When I have some spare time and motivation, maybe I will work on implementing the mentioned improvements. 

Cheers!

**Comment by minigranis** [comment]
Thanks, I know its a complex matter but your answer has given me an idea as what to expect.
